### PR TITLE
Added possibility to use tagged value 'icon' on actions to manage the icon_expr.

### PR DESCRIPTION
**Pull request by gbastien**
Hi @vincentfretin ,

this let use TaggedValue 'icon' on actions to manage the icon_expr available on every actions.

Please review/merge/...

Thank you! ;-)

Gauthier

### CODE REVIEW

**Comment by vincentfretin** [comment]
LGTM

**Comment by gbastien** [comment]
Hi @vincentfretin 

Did you know about this when you have a PR with some PEP8 spacing cleanup :, append ?w=1 to the end of the diff url :

https://github.com/collective/ArchGenXML/pull/4/files?w=1

;-)

See you!

Gauthier

**Comment by vincentfretin** [comment]
I didn't know, cool. But next time try to do a separate commit with whitespaces changes.
Do you know "git add -p"?

**Comment by gbastien** [comment]
I know I should have do that, but there was not much noise with white spaces changes so I proposed the PR like this ;-)

**Pull request merged**
