### PR TITLE
Make it possible to define an icon to use for a workflow transition

### PR DESCRIPTION
**Pull request by gbastien**
Now that DCWorkflow accepts to specify an icon for a transition, this makes it possible in AGX too.

Please @tdesvenain @zworkb @vincentfretin  review and merge ;-)

Gauthier

### CODE REVIEW

**Comment by vincentfretin** [comment]
Looks good, but if the icon tag definition is a new thing, you have to add it to TaggedValueSupport.py so we can regenerate the archgenxml_profile.xml with this new tag definition. Please add a changelog entry too.

**Comment by gbastien** [comment]
@vincentfretin I was on it ;-)

**Comment by vincentfretin** [comment]
After you've done bin/agx_argouml_profile, copy it to umltools/argouml/archgenxml_profile.xmi

**Comment by gbastien** [comment]
@vincentfretin 

OK, I added it to the xmi manually, I will change this by using your process.

Thank you,

Gauthier

**Comment by vincentfretin** [comment]
@zworkb you didn't add entries to the changelog for your recent commits. Can you please add them?

**Comment by gbastien** [comment]
@vincentfretin 

I updated the PR, generating the xmi using agx_argouml_profile changes the xmi a bit but it seems still consistent...

Gauthier

**Comment by gbastien** [comment]
Thank you ;-)

**Pull request merged**
